In [1]:
import pandas as pd

# READING VALUES

In [2]:
df=pd.read_csv("ipl2017.csv")

In [3]:
df.head()

mid        date                  venue               bat_team  \
0    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
1    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
2    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
3    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
4    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   

                     bowl_team      batsman   bowler  runs  wickets  overs  \
0  Royal Challengers Bangalore   SC Ganguly  P Kumar     1        0    0.1   
1  Royal Challengers Bangalore  BB McCullum  P Kumar     1        0    0.2   
2  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.2   
3  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.3   
4  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.4   

   runs_last_5  wickets_last_5  striker  non-striker  total  
0            1               0        0            0    222  
1            1               0        0            0    222  
2            2               0        0            0    222  
3            2               0        0            0    222  
4            2               0        0            0    222

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76014 entries, 0 to 76013
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   mid             76014 non-null  int64  
 1   date            76014 non-null  object 
 2   venue           76014 non-null  object 
 3   bat_team        76014 non-null  object 
 4   bowl_team       76014 non-null  object 
 5   batsman         76014 non-null  object 
 6   bowler          76014 non-null  object 
 7   runs            76014 non-null  int64  
 8   wickets         76014 non-null  int64  
 9   overs           76014 non-null  float64
 10  runs_last_5     76014 non-null  int64  
 11  wickets_last_5  76014 non-null  int64  
 12  striker         76014 non-null  int64  
 13  non-striker     76014 non-null  int64  
 14  total           76014 non-null  int64  
dtypes: float64(1), int64(8), object(6)
memory usage: 8.7+ MB


# CHECKING NULL VALUES

In [5]:
df.isnull().sum()

mid               0
date              0
venue             0
bat_team          0
bowl_team         0
batsman           0
bowler            0
runs              0
wickets           0
overs             0
runs_last_5       0
wickets_last_5    0
striker           0
non-striker       0
total             0
dtype: int64

# SPLITTING DATA

In [6]:
y=df["total"]

In [7]:
x=df.drop(['total','batsman','bowler','mid','date'],axis=1)

In [8]:
x

venue               bat_team  \
0                          M Chinnaswamy Stadium  Kolkata Knight Riders   
1                          M Chinnaswamy Stadium  Kolkata Knight Riders   
2                          M Chinnaswamy Stadium  Kolkata Knight Riders   
3                          M Chinnaswamy Stadium  Kolkata Knight Riders   
4                          M Chinnaswamy Stadium  Kolkata Knight Riders   
...                                          ...                    ...   
76009  Rajiv Gandhi International Stadium, Uppal         Mumbai Indians   
76010  Rajiv Gandhi International Stadium, Uppal         Mumbai Indians   
76011  Rajiv Gandhi International Stadium, Uppal         Mumbai Indians   
76012  Rajiv Gandhi International Stadium, Uppal         Mumbai Indians   
76013  Rajiv Gandhi International Stadium, Uppal         Mumbai Indians   

                         bowl_team  runs  wickets  overs  runs_last_5  \
0      Royal Challengers Bangalore     1        0    0.1            1   
1      Royal Challengers Bangalore     1        0    0.2            1   
2      Royal Challengers Bangalore     2        0    0.2            2   
3      Royal Challengers Bangalore     2        0    0.3            2   
4      Royal Challengers Bangalore     2        0    0.4            2   
...                            ...   ...      ...    ...          ...   
76009       Rising Pune Supergiant   121        7   19.2           40   
76010       Rising Pune Supergiant   127        7   19.3           46   
76011       Rising Pune Supergiant   128        7   19.4           47   
76012       Rising Pune Supergiant   129        7   19.5           48   
76013       Rising Pune Supergiant   129        8   19.6           47   

       wickets_last_5  striker  non-striker  
0                   0        0            0  
1                   0        0            0  
2                   0        0            0  
3                   0        0            0  
4                   0        0            0  
...               ...      ...          ...  
76009               0       40           12  
76010               0       46           12  
76011               0       47           12  
76012               0       47           13  
76013               1       47           13  

[76014 rows x 10 columns]

# CONVERTING CATEGORICAL VALUES

In [9]:
x=pd.get_dummies(x,columns=['bat_team','bowl_team','venue'],drop_first=True)

In [10]:
x.head()

runs  wickets  overs  runs_last_5  wickets_last_5  striker  non-striker  \
0     1        0    0.1            1               0        0            0   
1     1        0    0.2            1               0        0            0   
2     2        0    0.2            2               0        0            0   
3     2        0    0.3            2               0        0            0   
4     2        0    0.4            2               0        0            0   

   bat_team_Deccan Chargers  bat_team_Delhi Daredevils  \
0                         0                          0   
1                         0                          0   
2                         0                          0   
3                         0                          0   
4                         0                          0   

   bat_team_Gujarat Lions  ...  venue_Saurashtra Cricket Association Stadium  \
0                       0  ...                                             0   
1                       0  ...                                             0   
2                       0  ...                                             0   
3                       0  ...                                             0   
4                       0  ...                                             0   

   venue_Sawai Mansingh Stadium  \
0                             0   
1                             0   
2                             0   
3                             0   
4                             0   

   venue_Shaheed Veer Narayan Singh International Stadium  \
0                                                  0        
1                                                  0        
2                                                  0        
3                                                  0        
4                                                  0        

   venue_Sharjah Cricket Stadium  venue_Sheikh Zayed Stadium  \
0                              0                           0   
1                              0                           0   
2                              0                           0   
3                              0                           0   
4                              0                           0   

   venue_St George's Park  venue_Subrata Roy Sahara Stadium  \
0                       0                                 0   
1                       0                                 0   
2                       0                                 0   
3                       0                                 0   
4                       0                                 0   

   venue_SuperSport Park  venue_Vidarbha Cricket Association Stadium, Jamtha  \
0                      0                                                  0    
1                      0                                                  0    
2                      0                                                  0    
3                      0                                                  0    
4                      0                                                  0    

   venue_Wankhede Stadium  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  

[5 rows x 67 columns]

In [11]:
type(x)

pandas.core.frame.DataFrame

In [12]:
x.shape

(76014, 67)

# ONE-HOT ENCODING

In [13]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

ohe.fit_transform(df.venue.values.reshape(-1, 1)).toarray()

ohe = OneHotEncoder(drop='first')

In [14]:
ohe.fit_transform(df.bowl_team.values.reshape(-1, 1)).toarray()

ohe = OneHotEncoder(drop='first')

ohe.fit_transform(df.bowl_team.values.reshape(-1, 1)).toarray()

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
ohe.fit_transform(df.batsman.values.reshape(-1, 1)).toarray()

ohe = OneHotEncoder(drop='first')

ohe.fit_transform(df.batsman.values.reshape(-1, 1)).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
ohe.fit_transform(df.bowler.values.reshape(-1, 1)).toarray()

ohe = OneHotEncoder(drop='first')

ohe.fit_transform(df.bowler.values.reshape(-1, 1)).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# SPLITTING DATA

In [17]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y)

# SCALING

In [18]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

x_train=scaler.fit_transform(x_train)

x_test=scaler.transform(x_test)

# MODEL TRAINING

In [19]:
from sklearn.ensemble import RandomForestRegressor

forest=RandomForestRegressor()

In [20]:
forest.fit(x_train,y_train)

RandomForestRegressor()

In [21]:
forest.score(x_test,y_test)

0.9278823079079714

In [22]:
forest.score(x_train,y_train)

0.9884781034507942

# TESTING MODEL

In [23]:
data=pd.read_csv('test.csv')

In [24]:
data.head()

0  1   2   3  4   5   6  7  8  9  ...  57  58  59  60  61  62  63  64  \
0  150  3  15  20  2  50  20  1  0  0  ...   0   0   0   0   0   0   0   0   

   65  66  
0   0   0  

[1 rows x 67 columns]

In [25]:
forest.predict(data)

array([246.16])